reflinks = Dict(
    "[AMDGPU.jl]"                 => "https://github.com/JuliaGPU/AMDGPU.jl",
    "[CUDA.jl]"                   => "https://github.com/JuliaGPU/CUDA.jl",
    "[GTC19]"                     => "https://on-demand.gputechconf.com/gtc/2019/video/_/S9368/",
    "[IJulia]"                    => "https://github.com/JuliaLang/IJulia.jl",
    "[ImplicitGlobalGrid.jl]"     => "https://github.com/eth-cscs/ImplicitGlobalGrid.jl",
    "[JuliaCon19]"                => "https://pretalx.com/juliacon2019/talk/LGHLC3/",
    "[JuliaCon20a]"               => "https://www.youtube.com/watch?v=vPsfZUqI4_0",
    "[Julia CUDA paper 1]"        => "https://doi.org/10.1109/TPDS.2018.2872064",
    "[Julia CUDA paper 2]"        => "https://doi.org/10.1016/j.advengsoft.2019.02.002",
    "[Julia Plots documentation]" => "http://docs.juliaplots.org/latest/backends/",
    "[Julia Plots package]"       => "https://github.com/JuliaPlots/Plots.jl",
    "[Julia package manager]" => "https://docs.julialang.org/en/v1/stdlib/Pkg/",
    "[Julia REPL]"            => "https://docs.julialang.org/en/v1/stdlib/REPL/",
    "[MPI.jl]"                    => "https://github.com/JuliaParallel/MPI.jl",
    "[PASC19]"                    => "https://pasc19.pasc-conference.org/program/schedule/index.html%3Fpost_type=page&p=10&id=msa218&sess=sess144.html",
)
